python dual_inference.py \
	-target input_wavs/p284_024.wav \
	-source input_wavs/p341_008.wav \
	-output output_wavs/sig_1_den_0.2_0.1_tests \
	-output_name  blank\
	-attr OneShot/preprocess/data/VCTK/VCTK_attr.pkl \
	-oneshot_conf OneShot/config.yaml\
	-oneshot_model OneShot/models/vctk_22_kl_1_full_200k.ckpt\
	-sample_rate 22050 \
	-data_conf Waveglow/config.json \
	-waveglow_path Waveglow/models/waveglow_256channels_universal_v5.pt \
	-sigma 1\
	-denoiser_strength 0.1
