python dual_inference.py \
	-source=input_wavs/sources/
	-target=input_wavs/target/target.wav
	-output_dir=output_wavs/ \
	-attr=OneShot/models/vctk_colab/VCTK_attr.pkl \
	-oneshot_conf=OneShot/models/vctk_colab/.config.yaml \
	-oneshot_model=OneShot/models/vctk_22_kl_1_full_200k.ckpt \
	-sample_rate=22050 \
	-data_conf=Waveglow/config.json \
	-waveglow_path=Waveglow/models/waveglow_256channels_universal_v5.pt \
	-sigma=1\
	-denoiser_strength=0.1
